version: '3.9'
services:
  minio:
    container_name: Minio_test
    image: minio/minio:latest
    hostname: "minio"
    volumes:
      - ./minio:/minio_files
    env_file:
      - .env
    command: 'minio server /minio_files --console-address ":9001"'
    ports:
      - "9000:9000"
      - "9001:9001"

  createbuckets:
    container_name: Minio_bucket_test
    image: minio/mc:latest
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --quiet myminio/bucket;
      /usr/bin/mc anonymous set download myminio/bucket;
      "